# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vqe9tD1MLQZwX_uZzwzlriQdM_2e5zzb
"""

#App.py teste, serve para testar funcionalidades este arquivo ainda não esta finalizado, nem editado para melhor manutenabilidade do mesmo

import pandas as pd
import numpy as np
import joblib
from flask import Flask, request, jsonify
from sklearn.base import BaseEstimator, TransformerMixin

# --- DEFINIÇÃO DA CLASSE (Versão EXATA do Treino) ---
class ExtratorDeDatas(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_copy = X.copy()
        # Garante que é uma Series ou pega a primeira coluna do DF
        if isinstance(X_copy, pd.DataFrame):
            series = X_copy.iloc[:, 0]
        else:
            series = X_copy

        # Converte para datetime (dayfirst=True prioriza formato DD/MM/AAAA)
        dt_series = pd.to_datetime(series, dayfirst=True, errors='coerce')

        return pd.DataFrame({
            'mes': dt_series.dt.month,
            'dia_semana': dt_series.dt.dayofweek,
            'hora': dt_series.dt.hour,
            'dia_ano': dt_series.dt.day_of_year
        })

# --- CONFIGURAÇÃO DA API ---
app = Flask(__name__)
# Atualizado para o novo nome do arquivo solicitado
MODEL_PATH = 'modelo_atraso_voos_rf_res.pkl'
model = None

# Mapeamento: O que vem no JSON -> Nome da coluna no Modelo
DE_PARA_COLUNAS = {
    "companhia": "sg_empresa_icao",
    "origem": "sg_iata_origem",
    "destino": "sg_iata_destino",
    "data_partida": "dt_partida_prevista"
}

# Valores padrão para campos OBRIGATÓRIOS do modelo que NÃO vêm no JSON
# Importante: Esses valores influenciam a previsão. Foi utilizado a moda, mas pode ser melhora trocar valores
# Os valores esperados estão comentados, estes valores são apenas para aqueles que não viram no JSON
VALORES_PADRAO = {
    'nr_assentos_ofertados': np.int64(186),
    #'dt_partida_prevista': '19/01/2023 15:00',
    #'sg_iata_origem': 'GRU',
    #'sg_iata_destino': 'GRU',
    'nr_voo': '0248',
    #'sg_empresa_icao': 'AZU',
    'cd_tipo_linha': 'N',
    'sg_equipamento_icao': 'A320'}

try:
    print(f"Carregando modelo: {MODEL_PATH}...")
    model = joblib.load(MODEL_PATH)
    print("Modelo carregado com sucesso!")
except Exception as e:
    print(f"ERRO CRÍTICO ao carregar modelo: {e}")
    print("Dica: Verifique se o scikit-learn instalado é >= 1.3 (necessário para TargetEncoder).")

@app.route('/predict', methods=['POST'])
def predict():
    if not model:
        return jsonify({'status': 'error', 'message': 'Modelo indisponível no servidor.'}), 500

    try:
        data_json = request.get_json()
        if not data_json:
            return jsonify({'status': 'error', 'message': 'JSON vazio.'}), 400

        # 1. Validação dos campos esperados na interface (contrato simplificado)
        campos_esperados = list(DE_PARA_COLUNAS.keys()) # ['companhia', 'origem', 'destino', 'data_partida']
        missing_input = [col for col in campos_esperados if col not in data_json]

        if missing_input:
            return jsonify({
                'status': 'error',
                'message': f'Campos faltando na entrada: {missing_input}'
            }), 400

        # 2. Construção do dicionário final para o modelo
        dados_modelo = {}

        # A) Preenche campos mapeados (Renomeia)
        for campo_json, col_modelo in DE_PARA_COLUNAS.items():
            dados_modelo[col_modelo] = data_json[campo_json]

        # B) Preenche campos faltantes com Defaults
        for col_modelo, valor_padrao in VALORES_PADRAO.items():
            dados_modelo[col_modelo] = valor_padrao

        # 3. Criação do DataFrame
        df_input = pd.DataFrame([dados_modelo])

        # 4. Predição
        prediction = model.predict(df_input)[0]

        prob_delay = 0.0
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(df_input)[0]
            # Assume que a classe "1" (atraso) está no índice 1
            if len(probs) > 1:
                prob_delay = probs[1]
            else:
                prob_delay = probs[0]

        # 5. Formatação da Saída (Contrato do Java)
        # 1 = Atrasado, 0 = No Horário (ajuste o texto conforme necessidade)
        status_texto = "Atrasado" if prediction == 1 else "No Horário"

        return jsonify({
            "previsao": status_texto,
            "probabilidade": float(round(prob_delay, 2))
        })

    except Exception as e:
        # Log do erro no console do servidor para debug
        print(f"Erro no processamento: {e}")
        return jsonify({'status': 'error', 'message': str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=false)